// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.6.57.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace BarCode.Localization {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TextResources_en_US {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TextResources_en_US() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("BarCode.Localization.TextResources.en-US", typeof(TextResources_en_US).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string About_Context {
            get {
                return ResourceManager.GetString("About_Context", resourceCulture);
            }
        }
        
        internal static string About_Title {
            get {
                return ResourceManager.GetString("About_Title", resourceCulture);
            }
        }
        
        internal static string Add_Title {
            get {
                return ResourceManager.GetString("Add_Title", resourceCulture);
            }
        }
        
        internal static string Receipt_Title {
            get {
                return ResourceManager.GetString("Receipt_Title", resourceCulture);
            }
        }
        
        internal static string Splash_Cancel {
            get {
                return ResourceManager.GetString("Splash_Cancel", resourceCulture);
            }
        }
        
        internal static string Splash_FactoryNumberLabel {
            get {
                return ResourceManager.GetString("Splash_FactoryNumberLabel", resourceCulture);
            }
        }
        
        internal static string Splash_PasswordTitleLabel {
            get {
                return ResourceManager.GetString("Splash_PasswordTitleLabel", resourceCulture);
            }
        }
        
        internal static string Splash_SignIn {
            get {
                return ResourceManager.GetString("Splash_SignIn", resourceCulture);
            }
        }
        
        internal static string Splash_Title {
            get {
                return ResourceManager.GetString("Splash_Title", resourceCulture);
            }
        }
        
        internal static string Splash_UsernameTitleLabel {
            get {
                return ResourceManager.GetString("Splash_UsernameTitleLabel", resourceCulture);
            }
        }
    }
}
